### ISSUE TITLE
Several "WARN: unknown trace event" with trunk clang.

### ISSUE THREAD

**Issue by nico** [aras-p/ClangBuildAnalyzer#22]
I'm using clang built at http://reviews.llvm.org/rG64a362e7216a43e (from Oct 2). With that, ClangBuildAnalyzer prints these for every TU:

```
WARN: unknown trace event 'PerFunctionPasses' in 'out/src/gn/ninja_generated_file_target_writer_unittest.json', skipping.
WARN: unknown trace event 'PerModulePasses' in 'out/src/gn/ninja_generated_file_target_writer_unittest.json', skipping.
WARN: unknown trace event 'CodeGenPasses' in 'out/src/gn/ninja_generated_file_target_writer_unittest.json', skipping.
```

These were added in https://reviews.llvm.org/D68161 .

Looks like https://reviews.llvm.org/D69750 also adds "DebugType", but my compiler doesn't have that yet.

**Comment by aras-p** [comment]
@nico I did the code fix, but did not actually check if it works... :)
