### ISSUE TITLE
Support scanning for existing json files

### ISSUE THREAD

**Issue by xzxzzxzxzca** [aras-p/ClangBuildAnalyzer#46]
It would be nice to have an option to just start the tool on an existing collection of profiling files in the build directory instead of capturing them only between the start/stop cycle. Current workflow does not play well with incremental builds where most of the sources may be already processed with their build time stats already captured. In order to use the clang's profiling information one has to always start the build from scratch which doesn't seem to be strictly necessary.

**Comment by ben-craig** [comment]
There is a way to do this, though it isn't documented. Starting the
analyzer generates a file with a time stamp. You can set the time stamp to
zero, and then stop will look at all available json files.

**Comment by xzxzzxzxzca** [comment]
> You can set the time stamp to zero, and then stop will look at all available json files.

Thanks! That's an interesting workaround, seems usable enough.
Although, I still wish there would be a straightforward and more "official" to do this rather trivial task :)

**Comment by aras-p** [comment]
Added `--all` mode with #47
