### ISSUE TITLE
Latest tagged release does not have support for --all flag

### ISSUE THREAD

**Issue by bjacklyn** [aras-p/ClangBuildAnalyzer#67]
The README mentions the flag (merged to master in Oct 2020), but the latest release v1.2.0 (March 2020) doesn't have support for it. Discovered this after much confusion, and then looking at the pull requests & source code. Can we get a new release/tag? :)

`--all` was introduced in https://github.com/aras-p/ClangBuildAnalyzer/pull/47

**Comment by aras-p** [comment]
Ah yeah, here's 1.3.0: https://github.com/aras-p/ClangBuildAnalyzer/releases/tag/v1.3.0
